"""empty message

Revision ID: 13653dd3a632
Revises: 7b004e250a40
Create Date: 2021-01-26 12:18:04.488220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13653dd3a632'
down_revision = '7b004e250a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('suit', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'suit')
    # ### end Alembic commands ###
