"""empty message

Revision ID: 29dbe0fcb481
Revises: ffdc0a98111c
Create Date: 2021-01-25 18:50:44.263924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dbe0fcb481'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('query')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
