"""empty message

Revision ID: 565f5da57bea
Revises: e369d842a8ae
Create Date: 2021-01-26 12:55:57.525780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565f5da57bea'
down_revision = 'e369d842a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('suit', sa.String(length=12), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('api_endpoint', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_endpoint'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
