"""empty message

Revision ID: 1f63311e5838
Revises: e8d9037dcd26
Create Date: 2021-02-09 20:48:37.702965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f63311e5838'
down_revision = 'e8d9037dcd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('astrology', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('element', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('reversed_career_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_career_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_finances_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_finances_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_general_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_genereal_quote', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('reversed_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_love_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('reversed_love_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_career_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_career_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_finances_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_finances_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_general_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_genereal_quote', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_love_keywords', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('upright_love_meaning', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('value', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('zodiac', sa.String(), nullable=True))
    op.drop_constraint('cards_api_endpoint_key', 'cards', type_='unique')
    op.drop_column('cards', 'api_endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('api_endpoint', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.create_unique_constraint('cards_api_endpoint_key', 'cards', ['api_endpoint'])
    op.drop_column('cards', 'zodiac')
    op.drop_column('cards', 'value')
    op.drop_column('cards', 'upright_love_meaning')
    op.drop_column('cards', 'upright_love_keywords')
    op.drop_column('cards', 'upright_keywords')
    op.drop_column('cards', 'upright_genereal_quote')
    op.drop_column('cards', 'upright_general_meaning')
    op.drop_column('cards', 'upright_finances_meaning')
    op.drop_column('cards', 'upright_finances_keywords')
    op.drop_column('cards', 'upright_career_meaning')
    op.drop_column('cards', 'upright_career_keywords')
    op.drop_column('cards', 'reversed_love_meaning')
    op.drop_column('cards', 'reversed_love_keywords')
    op.drop_column('cards', 'reversed_keywords')
    op.drop_column('cards', 'reversed_genereal_quote')
    op.drop_column('cards', 'reversed_general_meaning')
    op.drop_column('cards', 'reversed_finances_meaning')
    op.drop_column('cards', 'reversed_finances_keywords')
    op.drop_column('cards', 'reversed_career_meaning')
    op.drop_column('cards', 'reversed_career_keywords')
    op.drop_column('cards', 'element')
    op.drop_column('cards', 'description')
    op.drop_column('cards', 'astrology')
    # ### end Alembic commands ###
