"""empty message

Revision ID: 4932fadf4abb
Revises: 1f63311e5838
Create Date: 2021-02-11 15:39:52.922527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4932fadf4abb'
down_revision = '1f63311e5838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('deck', sa.Text(), nullable=False),
    sa.Column('suit', sa.Text(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('upright_keywords', sa.Text(), nullable=False),
    sa.Column('upright_general_meaning', sa.Text(), nullable=False),
    sa.Column('upright_genereal_quote', sa.Text(), nullable=False),
    sa.Column('upright_career_keywords', sa.Text(), nullable=False),
    sa.Column('upright_love_keywords', sa.Text(), nullable=False),
    sa.Column('upright_finances_keywords', sa.Text(), nullable=False),
    sa.Column('upright_career_meaning', sa.Text(), nullable=False),
    sa.Column('upright_love_meaning', sa.Text(), nullable=False),
    sa.Column('upright_finances_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_keywords', sa.Text(), nullable=False),
    sa.Column('reversed_general_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_genereal_quote', sa.Text(), nullable=True),
    sa.Column('reversed_career_keywords', sa.Text(), nullable=False),
    sa.Column('reversed_love_keywords', sa.Text(), nullable=False),
    sa.Column('reversed_finances_keywords', sa.Text(), nullable=False),
    sa.Column('reversed_career_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_love_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_finances_meaning', sa.Text(), nullable=False),
    sa.Column('astrology', sa.Text(), nullable=True),
    sa.Column('element', sa.Text(), nullable=True),
    sa.Column('zodiac', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
